name: ML Pipeline CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies by Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root

    - name: Lint with flake8 all day5 files
      run: |
        poetry run flake8 day5 --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 day5 --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
        
    - name: Format check with black all all day5 files
      run: |
        poetry run black --check day5
        
    - name: Run test all all day5 files
      run: |
        poetry run pytest day5 -v
